import type { Metadata } from "next";
import { Outfit, Geist_Mono, Inter, Poppins } from "next/font/google";
// import { Outfit, Inter } from "next/font/google";
import "./globals.css";


// const inter = Inter({
//   subsets: ['latin'],
//   variable: '--font-inter',
// })


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '500','700'],
  variable: "--font-poppins"

})

// const outfit = Outfit({
//   subsets: ['latin'],
//   variable: "--font-outfit"
// })

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistMono.variable} `} 
      >
        {children}
      </body>
    </html>
  );
}
